name: qgsrepo
version: '0.1.4'
summary: A simple QGIS repository generator written in Rust
description: |
  A single binary that allows to generate a QGIS repository index XML file
  for a plugins directory by extracting metadata from plugins archives.
grade: stable
confinement: strict

apps:
  qgsrepo:
    command: qgsrepo
    completer: share/bash-completion/completions/qgsrepo
    plugs: [ home ]

parts:
  completer:
    plugin: dump
    source: snap/local
  qgsrepo:
    plugin: nil
    source: .
    build-packages:
      - cargo
    override-build: |
      cargo build --release
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      cp target/release/qgsrepo $SNAPCRAFT_PART_INSTALL/bin/
      strip $SNAPCRAFT_PART_INSTALL/bin/qgsrepo
