name: qgsrepo
version: '0.1.3'
summary: A simple QGIS repository generator written in Rust
description: |
  A single binary that allows to generate a QGIS repository index XML file
  for a plugins directory by extracting metadata from plugins archives.
grade: stable
confinement: strict

apps:
  qgsrepo:
    command: qgsrepo
    plugs: [ home ]

parts:
  qgsrepo:
    plugin: rust
    rust-channel: stable
    source: https://github.com/mentaljam/qgsrepo.git
    install: |
      strip $SNAPCRAFT_PART_INSTALL/bin/qgsrepo
